name: site-security-scan
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: Checkout
      uses: actions/checkout@v2 
    - run: echo '${{ github.workspace }}/zap-rules.tsv'
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: "https://www.zaproxy.org/"
        rules_file_name: '${{ github.workspace }}/zap-rules.tsv'
        cmd_options: '-a'
